[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tasks"
version = "0.1.0"
authors = ["omitida"]
description = "A simple task management application"
requires-python = ">=3.10"
readme = "README.md"
